BC_CATEGORIES = {
    "NOBC": ["NOBC", "NOBC", "NOBC"],
    "CONTINUER": ["CONTINUER", "CONTINUER", "BC"],
    "UNDERSTANDING": ["UNDERSTANDING", "UNDERSTANDING", "BC"],
    "AFFIRMATIVE": ["EMPATHETIC", "AFFIRMATIVE", "BC"],
    "NEGATIVE_SURPRISE": ["EMPATHETIC", "NEGATIVE_SURPRISE", "BC"],
    "POSITIVE_SURPRISE": ["EMPATHETIC", "POSITIVE_SURPRISE", "BC"],
    "REQUEST_CONFIRMATION": ["EMPATHETIC", "REQUEST_CONFIRMATION", "BC"],
    "ASSESSMENT": ["EMPATHETIC", "ASSESSMENT", "BC"],
}

SWBD_BC_CATEGORIES = {
    "NOBC": ["NOBC", "NOBC", "NOBC"],
    "CONTINUER": ["CONTINUER", "CONTINUER", "BC"],
    "ASSESSMENT": ["ASSESSMENT", "ASSESSMENT", "BC"],
}
